// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhI9RBwL56phQ7Utm1ZcdvwD0YQxZzxhc',
    appId: '1:263187104449:web:fdf4cb09403aa657fd0a40',
    messagingSenderId: '263187104449',
    projectId: 'gamer-flutter',
    authDomain: 'gamer-flutter.firebaseapp.com',
    storageBucket: 'gamer-flutter.appspot.com',
    measurementId: 'G-HPQV7PHQXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJtaMmY6uyO_TG_WYaI7C3Y-yfFs6yvPo',
    appId: '1:263187104449:android:10110120e9882485fd0a40',
    messagingSenderId: '263187104449',
    projectId: 'gamer-flutter',
    storageBucket: 'gamer-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_U8NOcxhHMCU4_f_QBfZT-Isa1wZa7Is',
    appId: '1:263187104449:ios:152c8906f89cf17dfd0a40',
    messagingSenderId: '263187104449',
    projectId: 'gamer-flutter',
    storageBucket: 'gamer-flutter.appspot.com',
    iosBundleId: 'com.example.blogAplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_U8NOcxhHMCU4_f_QBfZT-Isa1wZa7Is',
    appId: '1:263187104449:ios:152c8906f89cf17dfd0a40',
    messagingSenderId: '263187104449',
    projectId: 'gamer-flutter',
    storageBucket: 'gamer-flutter.appspot.com',
    iosBundleId: 'com.example.blogAplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhI9RBwL56phQ7Utm1ZcdvwD0YQxZzxhc',
    appId: '1:263187104449:web:d8408fc598fcc6bdfd0a40',
    messagingSenderId: '263187104449',
    projectId: 'gamer-flutter',
    authDomain: 'gamer-flutter.firebaseapp.com',
    storageBucket: 'gamer-flutter.appspot.com',
    measurementId: 'G-17QJ10JBCX',
  );
}
